// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "../ui.h"

void ui_IMU_screen_init(void)
{
    ui_IMU = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IMU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_IMU, &ui_img_round_imu_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_IMU);
    lv_obj_set_width(ui_Button1, 10);
    lv_obj_set_height(ui_Button1, 10);
    lv_obj_set_x(ui_Button1, -2);
    lv_obj_set_y(ui_Button1, -58);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIMUmy = lv_btn_create(ui_IMU);
    lv_obj_set_width(ui_ButtonIMUmy, 100);
    lv_obj_set_height(ui_ButtonIMUmy, 25);
    lv_obj_set_x(ui_ButtonIMUmy, 0);
    lv_obj_set_y(ui_ButtonIMUmy, 160);
    lv_obj_set_align(ui_ButtonIMUmy, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonIMUmy, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIMUmy, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIMUmy, lv_color_hex(0x73E5EF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIMUmy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIMUother = lv_btn_create(ui_IMU);
    lv_obj_set_width(ui_ButtonIMUother, 50);
    lv_obj_set_height(ui_ButtonIMUother, 12);
    lv_obj_set_x(ui_ButtonIMUother, 0);
    lv_obj_set_y(ui_ButtonIMUother, -30);
    lv_obj_set_align(ui_ButtonIMUother, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonIMUother, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIMUother, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIMUother, lv_color_hex(0xFAFD8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIMUother, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIMUstart = lv_btn_create(ui_IMU);
    lv_obj_set_width(ui_ButtonIMUstart, 100);
    lv_obj_set_height(ui_ButtonIMUstart, 37);
    lv_obj_set_x(ui_ButtonIMUstart, 0);
    lv_obj_set_y(ui_ButtonIMUstart, -5);
    lv_obj_set_align(ui_ButtonIMUstart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIMUstart, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_border_color(ui_ButtonIMUstart, lv_color_hex(0x5D5959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonIMUstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonIMUstart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIMUstart, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonIMUstart, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ButtonIMUstart, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_ButtonIMUstart, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(ui_ButtonIMUstart, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelButtonIMUstart = lv_label_create(ui_ButtonIMUstart);
    lv_obj_set_width(ui_LabelButtonIMUstart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonIMUstart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonIMUstart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonIMUstart, "START");
    lv_obj_set_style_text_color(ui_LabelButtonIMUstart, lv_color_hex(0x030101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonIMUstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_IMU);
    lv_obj_set_width(ui_Panel1, 180);
    lv_obj_set_height(ui_Panel1, 178);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -111);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonshadow = lv_btn_create(ui_IMU);
    lv_obj_set_width(ui_Buttonshadow, 10);
    lv_obj_set_height(ui_Buttonshadow, 10);
    lv_obj_set_x(ui_Buttonshadow, -2);
    lv_obj_set_y(ui_Buttonshadow, -58);
    lv_obj_set_align(ui_Buttonshadow, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Buttonshadow, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Buttonshadow, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Buttonshadow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonshadow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonIMUstart, ui_event_ButtonIMUstart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IMU, ui_event_IMU, LV_EVENT_ALL, NULL);

}
