// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "../ui.h"

void ui_ScreenIR_screen_init(void)
{
    ui_ScreenIR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenIR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageIRbg = lv_img_create(ui_ScreenIR);
    lv_img_set_src(ui_ImageIRbg, &ui_img_bg1_png);
    lv_obj_set_width(ui_ImageIRbg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageIRbg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageIRbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIRbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIRbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelIRnotice = lv_label_create(ui_ScreenIR);
    lv_obj_set_width(ui_LabelIRnotice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIRnotice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIRnotice, 2);
    lv_obj_set_y(ui_LabelIRnotice, -32);
    lv_obj_set_align(ui_LabelIRnotice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIRnotice, "         Click the button \nbelow to begin the learning");
    lv_obj_set_style_text_color(ui_LabelIRnotice, lv_color_hex(0xEB2323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIRnotice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIRnotice, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageIR = lv_img_create(ui_ScreenIR);
    lv_img_set_src(ui_ImageIR, &ui_img_img_ir_png);
    lv_obj_set_width(ui_ImageIR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageIR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageIR, -2);
    lv_obj_set_y(ui_ImageIR, -92);
    lv_obj_set_align(ui_ImageIR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageIR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageIR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageIR, 200);

    ui_ButtonIR = lv_btn_create(ui_ScreenIR);
    lv_obj_set_width(ui_ButtonIR, 133);
    lv_obj_set_height(ui_ButtonIR, 47);
    lv_obj_set_x(ui_ButtonIR, -2);
    lv_obj_set_y(ui_ButtonIR, 70);
    lv_obj_set_align(ui_ButtonIR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonIR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonIR, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIR, lv_color_hex(0x3A4750), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonIR, lv_color_hex(0x303841), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonIR, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_ButtonIR, lv_color_hex(0x303841), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonIR, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelButtonIR = lv_label_create(ui_ButtonIR);
    lv_obj_set_width(ui_LabelButtonIR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonIR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonIR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonIR, "OK, Let's Go");
    lv_obj_set_style_text_color(ui_LabelButtonIR, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonIR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonIR, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenIR, ui_event_ScreenIR, LV_EVENT_ALL, NULL);

}
