// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "../ui.h"

void ui_ScreenNet_screen_init(void)
{
    ui_ScreenNet = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenNet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageNet = lv_img_create(ui_ScreenNet);
    lv_img_set_src(ui_ImageNet, &ui_img_bg1_png);
    lv_obj_set_width(ui_ImageNet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageNet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageNet, -7);
    lv_obj_set_y(ui_ImageNet, -4);
    lv_obj_set_align(ui_ImageNet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNet, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imagecode = lv_img_create(ui_ScreenNet);
    lv_img_set_src(ui_Imagecode, &ui_img_code_demo_png);
    lv_obj_set_width(ui_Imagecode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imagecode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Imagecode, -2);
    lv_obj_set_y(ui_Imagecode, 39);
    lv_obj_set_align(ui_Imagecode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imagecode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imagecode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelcode = lv_label_create(ui_ScreenNet);
    lv_obj_set_width(ui_Labelcode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelcode, 2);
    lv_obj_set_y(ui_Labelcode, -85);
    lv_obj_set_align(ui_Labelcode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelcode, "Scan the QR Code to provision");
    lv_obj_set_style_text_color(ui_Labelcode, lv_color_hex(0xEB2323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelcode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelcode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenNet, ui_event_ScreenNet, LV_EVENT_ALL, NULL);

}
