// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "../ui.h"

void ui_watch_digital_screen_init(void)
{
    ui_watch_digital = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_watch_digital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_1 = lv_img_create(ui_watch_digital);
    lv_img_set_src(ui_bg_1, &ui_img_bg1_png);
    lv_obj_set_width(ui_bg_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour_group = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_hour_group, 289);
    lv_obj_set_height(ui_hour_group, 222);
    lv_obj_clear_flag(ui_hour_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hour_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_hour_1 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_1, -23);
    lv_obj_set_y(ui_label_hour_1, 60);
    lv_label_set_text(ui_label_hour_1, "");
    lv_obj_set_style_text_color(ui_label_hour_1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_1, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_hour_2 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_2, 93);
    lv_obj_set_y(ui_label_hour_2, 60);
    lv_label_set_text(ui_label_hour_2, "");
    lv_obj_set_style_text_color(ui_label_hour_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_2, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_min = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_min, 204);
    lv_obj_set_y(ui_label_min, 156);
    lv_label_set_text(ui_label_min, "27");
    lv_obj_set_style_text_color(ui_label_min, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_min, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_current = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_current, 30);
    lv_obj_set_y(ui_label_current, 106);
    lv_label_set_text(ui_label_current, "01q");
    lv_obj_set_style_text_color(ui_label_current, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_current, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_voteage = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_voteage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_voteage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_voteage, 30);
    lv_obj_set_y(ui_label_voteage, 136);
    lv_label_set_text(ui_label_voteage, "02b");
    lv_obj_set_style_text_color(ui_label_voteage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_voteage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_voteage, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_temperature = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_temperature, 30);
    lv_obj_set_y(ui_label_temperature, 166);
    lv_label_set_text(ui_label_temperature, "03a");
    lv_obj_set_style_text_color(ui_label_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_temperature, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_battery_group = ui_batterygroup_create(ui_watch_digital);
    lv_obj_set_x(ui_battery_group, 0);
    lv_obj_set_y(ui_battery_group, 20);



    ui_date_group = ui_dategroup_create(ui_watch_digital);
    lv_obj_set_x(ui_date_group, 58);
    lv_obj_set_y(ui_date_group, 53);



    ui_weather_group_1 = ui_weathergroup1_create(ui_watch_digital);
    lv_obj_set_x(ui_weather_group_1, -25);
    lv_obj_set_y(ui_weather_group_1, 59);


    lv_img_set_src(ui_comp_get_child(ui_weather_group_1, UI_COMP_WEATHERGROUP1_CLOUD_FOG_1), &ui_img_weather_sun_cloud_png);

    ui_step_group = ui_stepgroup_create(ui_watch_digital);
    lv_obj_set_x(ui_step_group, -13);
    lv_obj_set_y(ui_step_group, -55);



    ui_daily_mission_group = ui_dailymissiongroup_create(ui_watch_digital);
    lv_obj_set_x(ui_daily_mission_group, 0);
    lv_obj_set_y(ui_daily_mission_group, 0);

    lv_label_set_text(ui_comp_get_child(ui_daily_mission_group, UI_COMP_DAILYMISSIONGROUP_MISSION_PERCENT), "80%");

    lv_img_set_src(ui_comp_get_child(ui_daily_mission_group, UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_IMAGE),
                   &ui_img_volume_png);
    lv_obj_set_x(ui_comp_get_child(ui_daily_mission_group, UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_IMAGE), 6);
    lv_obj_set_y(ui_comp_get_child(ui_daily_mission_group, UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_IMAGE), 72);

    lv_arc_set_value(ui_comp_get_child(ui_daily_mission_group, UI_COMP_DAILYMISSIONGROUP_DAILY_MISSION_ARC), 80);


    ui_button_top = ui_buttontop_create(ui_watch_digital);
    lv_obj_set_x(ui_button_top, 129);
    lv_obj_set_y(ui_button_top, -98);

    lv_img_set_src(ui_comp_get_child(ui_button_top, UI_COMP_BUTTONTOP_BUTTON_TOP_ICON), &ui_img_act013_png);

    lv_obj_set_style_img_recolor(ui_comp_get_child(ui_button_top, UI_COMP_BUTTONTOP_LINE), lv_color_hex(0x000000),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_comp_get_child(ui_button_top, UI_COMP_BUTTONTOP_LINE), 255,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_down = ui_buttondown_create(ui_watch_digital);
    lv_obj_set_x(ui_button_down, 124);
    lv_obj_set_y(ui_button_down, 112);

    lv_img_set_src(ui_comp_get_child(ui_button_down, UI_COMP_BUTTONDOWN_BUTTON_DOWN_ICON), &ui_img_net_png);

    lv_obj_set_style_img_recolor(ui_comp_get_child(ui_button_down, UI_COMP_BUTTONDOWN_LINE), lv_color_hex(0x000000),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_comp_get_child(ui_button_down, UI_COMP_BUTTONDOWN_LINE), 255,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec_dot = lv_img_create(ui_watch_digital);
    lv_img_set_src(ui_sec_dot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_sec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec_dot, 0);
    lv_obj_set_y(ui_sec_dot, -190);
    lv_obj_set_align(ui_sec_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_sec_dot, 4, 194);

    ui_CTpoweroff = lv_obj_create(ui_watch_digital);
    lv_obj_remove_style_all(ui_CTpoweroff);
    lv_obj_set_width(ui_CTpoweroff, 360);
    lv_obj_set_height(ui_CTpoweroff, 360);
    lv_obj_set_align(ui_CTpoweroff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CTpoweroff, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CTpoweroff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CTpoweroff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CTpoweroff, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CTpower = lv_obj_create(ui_CTpoweroff);
    lv_obj_remove_style_all(ui_CTpower);
    lv_obj_set_width(ui_CTpower, 353);
    lv_obj_set_height(ui_CTpower, 82);
    lv_obj_set_x(ui_CTpower, 0);
    lv_obj_set_y(ui_CTpower, -54);
    lv_obj_set_align(ui_CTpower, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CTpower, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CTpower, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CTpower, lv_color_hex(0x464141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CTpower, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWpoweroff = lv_switch_create(ui_CTpower);
    lv_obj_set_width(ui_SWpoweroff, 173);
    lv_obj_set_height(ui_SWpoweroff, 72);
    lv_obj_set_x(ui_SWpoweroff, 47);
    lv_obj_set_y(ui_SWpoweroff, 0);
    lv_obj_set_align(ui_SWpoweroff, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SWpoweroff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWpoweroff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWpoweroff, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_SWpoweroff, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWpoweroff, lv_color_hex(0xAF6D6D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SWpoweroff, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_SWpoweroff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWpoweroff, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWpoweroff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SWpoweroff, &ui_img_1630624692, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_CTpower);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -101);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Power:");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CTfactory = lv_obj_create(ui_CTpoweroff);
    lv_obj_remove_style_all(ui_CTfactory);
    lv_obj_set_width(ui_CTfactory, 353);
    lv_obj_set_height(ui_CTfactory, 82);
    lv_obj_set_x(ui_CTfactory, 0);
    lv_obj_set_y(ui_CTfactory, 29);
    lv_obj_set_align(ui_CTfactory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CTfactory, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CTfactory, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CTfactory, lv_color_hex(0x464141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CTfactory, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWfactory = lv_switch_create(ui_CTfactory);
    lv_obj_set_width(ui_SWfactory, 173);
    lv_obj_set_height(ui_SWfactory, 72);
    lv_obj_set_x(ui_SWfactory, 47);
    lv_obj_set_y(ui_SWfactory, 0);
    lv_obj_set_align(ui_SWfactory, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SWfactory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWfactory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWfactory, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_SWfactory, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWfactory, lv_color_hex(0xAF6D6D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SWfactory, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_SWfactory, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SWfactory, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SWfactory, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SWfactory, &ui_img_1630624692, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_CTfactory);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -101);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Factory\nReset:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button_top, ui_event_button_top_buttontop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_down, ui_event_button_down_buttondown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SWpoweroff, ui_event_SWpoweroff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SWfactory, ui_event_SWfactory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CTpoweroff, ui_event_CTpoweroff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watch_digital, ui_event_watch_digital, LV_EVENT_ALL, NULL);

}
