// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif
#include "bsp/bsp_esp_magnescreen.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

#define LV_EVENT_FACE_LOOK              (_LV_EVENT_LAST + 1)
#define LV_EVENT_FACE_ASK               (_LV_EVENT_LAST + 2)
#define LV_EVENT_FACE_THINK             (_LV_EVENT_LAST + 3)
#define LV_EVENT_FACE_RUNNING           (_LV_EVENT_LAST + 4)

void sec_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void left_Animation(lv_obj_t * TargetObject, int delay);
void right_Animation(lv_obj_t * TargetObject, int delay);
void opa_on_Animation(lv_obj_t * TargetObject, int delay);
void dots_Animation(lv_obj_t * TargetObject, int delay);
void top_Animation(lv_obj_t * TargetObject, int delay);
void cloud_Animation(lv_obj_t * TargetObject, int delay);
void blood2_Animation(lv_obj_t * TargetObject, int delay);
void blood1_Animation(lv_obj_t * TargetObject, int delay);
void heart_Animation(lv_obj_t * TargetObject, int delay);
void up_and_down_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_watch_digital
void ui_watch_digital_screen_init(void);
void ui_event_watch_digital(lv_event_t * e);
extern lv_obj_t * ui_watch_digital;
extern lv_obj_t * ui_bg_1;
extern lv_obj_t * ui_hour_group;
extern lv_obj_t * ui_label_hour_1;
extern lv_obj_t * ui_label_hour_2;
extern lv_obj_t * ui_label_min;
extern lv_obj_t * ui_label_current;
extern lv_obj_t * ui_label_voteage;
extern lv_obj_t * ui_label_temperature;
extern lv_obj_t * ui_battery_group;
extern lv_obj_t * ui_date_group;
extern lv_obj_t * ui_weather_group_1;
extern lv_obj_t * ui_step_group;
extern lv_obj_t * ui_daily_mission_group;
void ui_event_button_top_buttontop(lv_event_t * e);
extern lv_obj_t * ui_button_top;
void ui_event_button_down_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down;
extern lv_obj_t * ui_sec_dot;
void ui_event_CTpoweroff(lv_event_t * e);
extern lv_obj_t * ui_CTpoweroff;
extern lv_obj_t * ui_CTpower;
void ui_event_SWpoweroff(lv_event_t * e);
extern lv_obj_t * ui_SWpoweroff;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_CTfactory;
void ui_event_SWfactory(lv_event_t * e);
extern lv_obj_t * ui_SWfactory;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_call
void ui_call_screen_init(void);
void ui_event_call(lv_event_t * e);
extern lv_obj_t * ui_call;
extern lv_obj_t * ui_bg_3;
extern lv_obj_t * ui_avatar;
extern lv_obj_t * ui_avatar_label;
extern lv_obj_t * ui_mute;
void ui_event_button_down2_buttondown(lv_event_t * e);
extern lv_obj_t * ui_button_down2;
extern lv_obj_t * ui_volume_group;
extern lv_obj_t * ui_volume_percent;
extern lv_obj_t * ui_volume_image;
extern lv_obj_t * ui_volume_arc;
// SCREEN: ui_measuing
void ui_measuing_screen_init(void);
void ui_event_measuing(lv_event_t * e);
extern lv_obj_t * ui_measuing;
extern lv_obj_t * ui_bg7;
extern lv_obj_t * ui_pulse_group3;
extern lv_obj_t * ui_measuring;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_blood_group;
extern lv_obj_t * ui_blood1;
extern lv_obj_t * ui_blood_fill;
extern lv_obj_t * ui_blood2;
void ui_event_x_button(lv_event_t * e);
extern lv_obj_t * ui_x_button;
extern lv_obj_t * ui_x;
// SCREEN: ui_ScreenIR
void ui_ScreenIR_screen_init(void);
void ui_event_ScreenIR(lv_event_t * e);
extern lv_obj_t * ui_ScreenIR;
extern lv_obj_t * ui_ImageIRbg;
extern lv_obj_t * ui_LabelIRnotice;
extern lv_obj_t * ui_ImageIR;
extern lv_obj_t * ui_ButtonIR;
extern lv_obj_t * ui_LabelButtonIR;
// SCREEN: ui_ScreenNet
void ui_ScreenNet_screen_init(void);
void ui_event_ScreenNet(lv_event_t * e);
extern lv_obj_t * ui_ScreenNet;
extern lv_obj_t * ui_ImageNet;
extern lv_obj_t * ui_Imagecode;
extern lv_obj_t * ui_Labelcode;
// SCREEN: ui_IMU
void ui_IMU_screen_init(void);
void ui_event_IMU(lv_event_t * e);
extern lv_obj_t * ui_IMU;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonIMUmy;
extern lv_obj_t * ui_ButtonIMUother;
void ui_event_ButtonIMUstart(lv_event_t * e);
extern lv_obj_t * ui_ButtonIMUstart;
extern lv_obj_t * ui_LabelButtonIMUstart;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Buttonshadow;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

void ui_event_face(lv_event_t *e);
void ui_send_sys_event(lv_obj_t *obj, lv_event_code_t event_code, void *user_data);

extern lv_obj_t * ui_Panel_face;
extern lv_obj_t * ui_face_canvas;

LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_weather_sun_cloud_png);    // assets/weather_sun_cloud.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_daily_mission_png);    // assets/daily_mission.png
LV_IMG_DECLARE(ui_img_volume_png);    // assets/volume.png
LV_IMG_DECLARE(ui_img_call1_png);    // assets/call1.png
LV_IMG_DECLARE(ui_img_btn_bg_1_png);    // assets/btn_bg_1.png
LV_IMG_DECLARE(ui_img_act013_png);    // assets/ACT013.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_btn_bg_3_png);    // assets/btn_bg_3.png
LV_IMG_DECLARE(ui_img_net_png);    // assets/net.png
LV_IMG_DECLARE(ui_img_sec_dot_png);    // assets/sec_dot.png
LV_IMG_DECLARE(ui_img_1630624692);    // assets/电源.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_ai_robot_png);    // assets/AI_robot.png
LV_IMG_DECLARE(ui_img_mute_png);    // assets/mute.png
LV_IMG_DECLARE(ui_img_unmute_png);    // assets/unmute.png
LV_IMG_DECLARE(ui_img_house_png);    // assets/house.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/wave2.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_x_png);    // assets/x.png
LV_IMG_DECLARE(ui_img_img_ir_png);    // assets/img_IR.png
LV_IMG_DECLARE(ui_img_code_demo_png);    // assets/code_demo.png
LV_IMG_DECLARE(ui_img_round_imu_png);    // assets/round_imu.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_btn_bg_2_png);    // assets/btn_bg_2.png
LV_IMG_DECLARE(ui_img_call2_png);    // assets/call2.png
LV_IMG_DECLARE(ui_img_heart2_png);    // assets/heart2.png
LV_IMG_DECLARE(ui_img_s1_png);    // assets/s1.png
LV_IMG_DECLARE(ui_img_s2_png);    // assets/s2.png
LV_IMG_DECLARE(ui_img_s3_png);    // assets/s3.png
LV_IMG_DECLARE(ui_img_s4_png);    // assets/s4.png
LV_IMG_DECLARE(ui_img_s5_png);    // assets/s5.png
LV_IMG_DECLARE(ui_img_s6_png);    // assets/s6.png
LV_IMG_DECLARE(ui_img_s7_png);    // assets/s7.png
LV_IMG_DECLARE(ui_img_s8_png);    // assets/s8.png
LV_IMG_DECLARE(ui_img_s9_png);    // assets/s9.png



LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
