// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "ui.h"

void ui_imu_start(lv_event_t * e)
{
	// Your code here
}

// void ui_event_SWpoweroff(lv_event_t * e)
// {

// 	// Your code here
// }
extern void wifi_credential_reset();
// void ui_event_SWfactoryreset(lv_event_t * e)
// {

// 	// Your code here
// }

void ui_event_SWpoweroff_function(lv_event_t * e)
{
	vTaskDelay(pdMS_TO_TICKS(300));
	bsp_power_off();
	// Your code here
}

void ui_event_SWfactoryreset_function(lv_event_t * e)
{
	vTaskDelay(pdMS_TO_TICKS(300));
	wifi_credential_reset();
	// Your code here
}
