// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Smartwatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_SWpoweroff_function(lv_event_t * e);
void ui_event_SWfactoryreset_function(lv_event_t * e);
void ui_imu_start(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
